sooperset/mcp-atlassian

- .env.example
- README.md
- pyproject.toml
- src/mcp_atlassian/config.py
- src/mcp_atlassian/confluence.py
- src/mcp_atlassian/jira.py
- src/mcp_atlassian/preprocessing.py
- src/mcp_atlassian/server.py
- src/mcp_atlassian/types.py
- uv.lock
- Jira integration with issue tracking and project management features
- HTML/Markdown content preprocessing and cleaning
- MCP-compliant server implementation
> feat: Implement MCP Atlassian Integration for Jira

- README.md
- src/mcp_atlassian/__init__.py
- src/mcp_atlassian/confluence.py
- src/mcp_atlassian/jira.py
- Adds command-line arguments for configuration (URLs, usernames, tokens)
- Supports environment file loading via --env-file flag
> Add CLI arguments and improve installation options

- .gitignore
- README.md
- src/mcp_atlassian/confluence.py
- src/mcp_atlassian/jira.py
- src/mcp_atlassian/server.py
modify resource listing to show only spaces and projects with user interaction
> fix: resource filtering

- src/mcp_atlassian/server.py
- Enhance Confluence space descriptions with space key and usage instructions
- Update Jira project descriptions to be more informative
- Add detailed examples and clarifications to tool input schemas
- Improve descriptions for Jira tools like get_issue, search, create_issue, and update_issue
- Provide more context for page_id and JQL query usage
> Feat: Improve resource and tool descriptions with more context and examples

- CHANGELOG.md
- README.md
- src/mcp_atlassian/__init__.py
- src/mcp_atlassian/jira.py
- src/mcp_atlassian/server.py
- tests/test_jira.py
credit: @phuongwd 
on top of #53 , update README.md and fix pre-commit erros
> feat: add comprehensive Epic linking support for Jira (credit: @phuongwd)

- src/mcp_atlassian/server.py
Improve JSON serialization and result formatting
- Add helper functions for formatting Confluence comments, Jira issues, and transitions
- Consistently use `ensure_ascii=False` in JSON serialization to support non-ASCII characters
- Standardize result formatting across different tool methods
- Enhance readability and consistency of API response structures
resolve: #54
> Fix: Prevent escaping of multibyte characters in JSON API responses

- src/mcp_atlassian/jira.py
- src/mcp_atlassian/server.py
This PR fixes issue #69 "Error while parsing Jira search response" where the MCP server would crash when a Jira search was performed with limited fields (e.g., only "summary,status"). The error occurred because the code expected the "issuetype" field to always be present in the response, but when users explicitly requested only certain fields, Jira's API would only return those fields.
- Added safe field access throughout `search_issues` function to handle missing fields gracefully
- Updated `get_epic_issues` function to handle missing issue type data
- Modified `format_issue` function in server.py to use .get() with default values
- Added automatic field expansion in the `jira_search` tool to ensure required fields are included
- Added proper error handling and meaningful default values …
> Fix Handle missing issuetype field in Jira search responses (#69)

- src/mcp_atlassian/jira/issues.py
- src/mcp_atlassian/jira/transitions.py
- tests/unit/jira/test_transitions.py
The MCP Jira transition API was failing with type errors when handling status transitions.
Enhanced transition handling to properly support both status names and IDs, with improved error handling and field management.
> Fix Jira Transition API Type Handling Issues

- src/mcp_atlassian/jira/issues.py
This PR addresses the error logged during Jira issue retrieval: "Error getting Jira fields: 'Jira' object has no attribute 'fields'". The error was occurring because the code was trying to access methods that might not exist on all Jira API adapters.
- Added attribute existence checks before calling methods on the Jira client
- Added robust error handling around epic information extraction
- Improved field ID fetching to handle API inconsistencies
- Added graceful fallbacks when operations fail
- All existing tests pass
- Manually verified that the error no longer appears in logs
Fixes #78
> Fix Jira get_issue error: 'Jira' object has no attribute 'fields'

- .env.example
- CHANGELOG.md
- README.md
- src/mcp_atlassian/__init__.py
- src/mcp_atlassian/confluence/client.py
- src/mcp_atlassian/confluence/config.py
- src/mcp_atlassian/server.py
- tests/unit/confluence/conftest.py
- tests/unit/confluence/test_client.py
- tests/unit/confluence/test_config.py
Hi,
Based on what you did for Jira authentication , I propose this implementation for the same feature for Confluence. 
I hope it helps
> Add authentication for Confluence Server/Data Center deployments

- README.md
> Update demo GIF

- README.md
TITC!  Thanks for a great repo
> Minor: Update README.md with Composer, Agent screencapture

- src/mcp_atlassian/models/jira.py
- tests/unit/jira/test_issues.py
- tests/unit/models/test_jira_models.py
> Fix pre-commit error and pytest

- src/mcp_atlassian/__init__.py
- src/mcp_atlassian/jira/client.py
- src/mcp_atlassian/server.py
- src/mcp_atlassian/utils/__init__.py
- src/mcp_atlassian/utils/io.py
- src/mcp_atlassian/utils/logging.py
- src/mcp_atlassian/utils/ssl.py
- src/mcp_atlassian/utils/urls.py
- tests/integration/test_ssl_verification.py
- tests/unit/utils/__init__.py
- tests/unit/utils/test_io.py
- tests/unit/utils/test_logging.py
- tests/unit/utils/test_ssl.py
- tests/unit/utils/test_urls.py
Improve code organization, maintainability, and testability of the utils module.
- Split utils into logical sub-modules (io, logging, ssl, urls)
- Added new `setup_logging` function with handler cleanup and configurable log levels
- Improved URL detection for Atlassian cloud domains
- Added comprehensive tests for each sub-module
> Refactor utils module into specialized sub-modules

- src/mcp_atlassian/jira/boards.py
- src/mcp_atlassian/models/jira.py
- tests/unit/jira/test_boards.py
Add JiraBoards class and a single method `get_all_agile_boards`. 
I will add more method about jira "board" and "sprint" if this PR is review ok.
> Add JiraBoards and get_all_agile_boards tool

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/post-create.sh
- .devcontainer/post-start.sh
- CONTRIBUTING.md
This adds a devcontainer setup and some guidance to equalise the development environment accross local VSCode and Github codespaces.
> Added devcontainer

- .env.example
- README.md
- src/mcp_atlassian/server.py
- tests/test_server.py
This will allow basic auth parameters to be used with on-prem confluence
> On prem confluence with basic auth is also made available

- src/mcp_atlassian/jira/issues.py
I was not able to use JIRA Issue creation without this change as the 'Components' field is mandatory in my JIRA setup. Cline for VS Code helped with fixing the issue.
> Update Jira issues handling

- src/mcp_atlassian/jira/users.py
- tests/unit/jira/test_users.py
Users are unable to start MCP from CLINE with Jira Data Center 9.x due to a Python C-level error: `timestamp too large to convert to C _PyTime_t`. This occurs during startup when attempting to get the current user's account ID, preventing Jira projects from being fetched.
This PR implements a workaround by replacing the `jira.myself()` call (from atlassian-python-api) with a direct API request using `requests`. The key difference is that we manually parse the JSON response without automatic timestamp conversion, avoiding the problematic conversion of extreme date values (like year 9999) returned by some Jira DC instances.
> Fix timestamp conversion error

- src/mcp_atlassian/server.py
The signature of the `read_resource` function should take in a `AnyUrl` and return `str`. Make the needed changes to match this.
> Fix read_resource

- src/mcp_atlassian/jira/issues.py
- src/mcp_atlassian/server.py
Hi, regarding #115 , this works for me locally.
> Support Jira "Component/s" field when creating the tickets

- src/mcp_atlassian/server.py
Fixes #206 
The confluence_get_page_children tool was failing with the error "cannot access local variable 'pages' where it is not associated with a value" due to improper indentation and missing error handling.
- Fixed indentation issues in the call_tool handler for confluence_get_page_children
- Added proper initialization of the 'pages' variable before the try block
- Added error handling to catch exceptions when fetching page children
- Restructured the code to ensure proper variable scope
- Added missing parameters (convert_to_markdown, start) to support all the tool's features
> Fix "cannot access local variable 'pages'" error in confluence_get_page_children tool

- src/mcp_atlassian/models/jira.py
- tests/unit/models/test_jira_models.py
Adds proper support for the Jira `timetracking` field, fixing issue #213 where this data was inaccessible in search results.
- Added `JiraTimetracking` model with snake_case fields mapped to Jira's camelCase API fields
- Added timetracking field to JiraIssue model
- Process timetracking data in API responses
- Return timetracking in simplified dict when requested
- Added comprehensive tests
Fixes #213
> Fix: Add proper support for Jira timetracking field (#213)

- src/mcp_atlassian/server.py
I'm not completely confident if this is the appropriate approach to resolve issue #211. Please provide feedback during code review on whether this solution makes sense.
> fix: windsurf parse error

- README.md
This PR enhances the `README.md` for improved clarity, structure, and user experience. The goal is to make onboarding smoother and information easier to find.
*   Added usage examples upfront.
*   Restructured the Quick Start Guide and installation instructions (emphasizing `uvx`).
*   Refined IDE configuration examples using `<details>` for better focus.
*   Improved the Resources/Tools and Troubleshooting sections.
*   General formatting and structural improvements for readability.
*   Faster onboarding and easier setup.
*   Clearer instructions and better discoverability of features.
*   More professional and maintainable documentation.
> Docs: Improve README Clarity, Structure, and Examples

- README.md
- src/mcp_atlassian/jira/__init__.py
- src/mcp_atlassian/jira/links.py
- src/mcp_atlassian/server.py
- tests/unit/jira/test_links.py
- Add LinksMixin class for Jira issue link operations
- Implement create_issue_link and remove_issue_link methods
- Add corresponding MCP tools for creating and removing issue links
- Integrate LinksMixin into JiraFetcher
- Add comprehensive unit tests for link operations
This PR adds support for Jira issue link operations to the MCP Atlassian server. It implements functionality to create and remove links between Jira issues, along with corresponding MCP tools that can be used by LLMs to manage issue relationships.
- Added `LinksMixin` class with methods for:
- Creating links between issues (`create_issue_link`)
- Removing links between issues (`remove_issue_link`)
- Integrated `LinksMixin` into the `JiraFetcher` class
- Added two new MCP tools:
- `jira_create_issue_link`: Creates a link …
> feat(jira): add issue link operations

- README.md
This PR enhances the README documentation with additional installation and configuration options to improve user experience for Docker users and macOS users with Homebrew. It makes the installation process more accessible to users with different preferences and environments.
Fixes: #
- Added Docker as Option 4 in the installation section, including repository cloning and image building instructions
- Added Docker configuration details in the IDE Integration section with two methods (environment variables and env file)
- Added Homebrew as an alternative installation method for uv on macOS
> Add Docker Installation Support and Homebrew Option for macOS

- src/mcp_atlassian/server.py
- src/mcp_atlassian/utils/logging.py
- tests/unit/test_server.py
- tests/unit/utils/test_masking.py
This PR implements enhanced startup connection feedback when initializing Atlassian services. It adds utilities for securely masking sensitive data and provides detailed logging of connection parameters while ensuring credentials are properly masked.
Fixes: #286
- Implemented sensitive data masking functionality in `utils/logging.py` 
- Added configuration parameter logging with proper security handling
- Enhanced the `server_lifespan` function to provide detailed connection information
- Added comprehensive error handling for configuration issues during initialization
- Ensured sensitive information (API tokens, personal tokens) is masked in logs
> implement enhanced startup connection feedback with sensitive data masking

- pyproject.toml
- src/mcp_atlassian/jira/fields.py
- src/mcp_atlassian/server.py
- tests/unit/jira/test_fields.py
- uv.lock
Add a `jira_search_fields` tool that can fuzzy search fields.
- feat: add jira_search_fields
- test: add tests for jira_search_fields
- chore: add `thefuzz` dependency
> feat: add jira_search_fields

- src/mcp_atlassian/servers/confluence.py
- src/mcp_atlassian/servers/jira.py
This PR refactors the Confluence and Jira tool implementations (`confluence.py`, `jira.py`) to align their function docstrings and parameter descriptions with the canonical definitions stored in `metadata.py`.
Relevant: #304 
- Updated primary function docstrings in `confluence.py` and `jira.py` to match the `description` field from `metadata.py` for each tool.
- Modified function parameters in both files to use `Annotated[<type>, Field(description="...")]`.
- Copied the specific parameter descriptions from `metadata.py` (`inputSchema.properties.<param>.description`) into the corresponding `Field` annotations.
- Ensured all required tool parameters now have explicit `Annotated` type hints with descriptions from the metadata.
> Refactor: Align Confluence/Jira Tool Descriptions and Parameters with Metadata

- README.md
Refactors the `README.md` to streamline the setup process by focusing exclusively on Docker for installation and configuration, as per the agreed resolution plan. This simplifies the getting started experience for users by removing alternative installation methods (pip, uvx) from the main guide.
-   Removed `pip`, `uvx`, and `Smithery` installation sections from README.
-   Added Docker `pull` and `build` instructions.
-   Updated Configuration section to explain Docker environment variable methods (`--env-file` and `-e`).
-   Replaced IDE integration examples with Docker-specific configurations.
-   Updated Troubleshooting tips for Docker context.
-   Adjusted Contributing section mention for clarity.
-   [ ] N/A (Documentation change)
-   [ ] N/A (Documentation change)
-   [x] Manual …
> Docs: Refactor README for Docker-Focused Installation

- src/mcp_atlassian/__init__.py
This PR fixes issue #327 where users running `mcp-atlassian` via Docker couldn't disable SSL certificate verification using the `JIRA_SSL_VERIFY=false` environment variable. The environment variables were being overwritten by the default CLI flag values.
Fixes: #327
- Modified `__init__.py` to only set environment variables for SSL verification when CLI flags are explicitly provided
- Added helper function `was_option_provided()` to check if a click option was explicitly provided or using default value
> Fix SSL verification environment variables in Docker containers

- Dockerfile
This PR optimizes the Docker image size for the MCP Atlassian server by cleaning up unnecessary files from the virtual environment and switching to Alpine-based images. It also improves security by running the application as a non-root user. These changes address the issue of large Docker image sizes and follow best practices for containerization.
- Switches Docker base images to Alpine variants for smaller image size.
- Adds a cleanup step in the builder stage to remove `__pycache__`, `.pyc`, and `.pyo` files from the virtual environment.
- Creates and uses a non-root `app` user in the final image for improved security.
- Reduces the image size (293MB --> 147MB)
> feat(docker): optimize docker image size

- src/mcp_atlassian/server.py
- tests/unit/test_server.py
Adds a dedicated `/healthz` HTTP endpoint for use as a Kubernetes health probe when the server is running in SSE transport mode. This endpoint returns a simple 200 OK response, allowing Kubernetes readiness, liveness, and startup probes to function correctly even when the main `/sse` endpoint maintains a persistent connection.
Fixes: #359
- Add `health_check` async endpoint to `src/mcp_atlassian/server.py` that returns HTTP 200 OK with body "OK".
- Register `/healthz` route in the Starlette app only when `--transport sse` is used.
- Add unit test (`test_sse_healthz_endpoint`) in `tests/unit/test_server.py` to verify the endpoint returns 200 OK and "OK" body.
> feat: Add /healthz endpoint for SSE Kubernetes probes (#359)

- README.md
- Add `uvx` command for easier OAuth setup.
- Streamline Claude Desktop config steps.
- Update Cursor config path.
Improves README clarity for OAuth setup and AI assistant configuration.
- Introduced `uvx mcp-atlassian@latest --oauth-setup` command.
- Simplified Claude Desktop config instructions.
- Updated Cursor config path.
> Docs: Update README Setup Instructions

- src/mcp_atlassian/__init__.py
sse with docker does not work
Fixes: #377
- Modified the server startup for SSE transport to bind to "0.0.0.0", allowing it to accept connections from any network interface. This change enhances accessibility for clients connecting to the server.
> fix: Update SSE transport to bind to all interfaces

- scripts/oauth_authorize.py
- src/mcp_atlassian/utils/oauth.py
This PR significantly improves the reliability, debuggability, and user experience of the Atlassian OAuth 2.0 authorization flow. It resolves critical issues such as the "501 Unsupported method ('GET')" error during callback, enhances logging for easier troubleshooting, and makes the overall process more robust.
Fixes: # (If you have an issue number, add it here)
- Corrected the HTTP method name in `CallbackHandler` (from `do_get` to `do_GET`) to properly handle Atlassian's OAuth callback, resolving 501 errors.
- Enhanced logging configuration in `scripts/oauth_authorize.py` to default to DEBUG level with line numbers, and ensured specific loggers (`oauth-authorize`, `mcp-atlassian.oauth`) also output detailed logs.
- Improved `CallbackHandler` to specifically filter for `/callback` …
> fix: Enhance Atlassian OAuth Flow, Callback Handling, and Logging

- src/mcp_atlassian/servers/confluence.py
This PR fixes compatibility issues with MCP clients (notably Cursor IDE) that struggle with `Union[str, None]` parameters in tool schemas. When string values are provided for optional parameters, some clients incorrectly expect `undefined` and raise type mismatch errors.
Refs: #389
- Changed optional string parameters from `str | None` to `str` with `default=""` in Confluence tools
- Added internal conversion of empty strings to `None` to maintain library behavior
- Affected parameters: `spaces_filter` in `confluence_search`, `parent_id` in `create_page` and `update_page`
> fix(confluence): Fix optional string params for client compatibility

- src/mcp_atlassian/__init__.py
- src/mcp_atlassian/utils/environment.py
Fixes the environment detection logic to properly recognize OAuth configurations for Jira and Confluence services.
- Updated `get_available_services` to properly check for all required OAuth environment variables
- Added explicit check for `ATLASSIAN_OAUTH_CLOUD_ID` which is critical for OAuth initialization
- Set OAuth configuration to take precedence over basic/token auth when present
- Fixed absolute import paths in `__init__.py`
> Fix: Improve OAuth configuration detection in environment checks

- README.md
updated the oauth setup with docker for the consistency
> docs: restore docker setup for oauth

- README.md
- src/mcp_atlassian/servers/jira.py
- tests/unit/servers/test_jira_server.py
This PR addresses the linting failure for #493. This introduces additional error handling, optimizes project filtering performance, enhances documentation, and strengthens test coverage.
- Added comprehensive try/except error handling to `jira_get_all_projects`.
- Optimized project filtering logic.
- Updated docstring for `jira_get_all_projects`.
- Added 4 new test cases for empty responses and error scenarios (API/network error, authentication error, configuration error).
> feat: fix linting issue and polish jira_get_all_projects PR

- src/mcp_atlassian/confluence/client.py
- src/mcp_atlassian/jira/client.py
- src/mcp_atlassian/servers/confluence.py
- src/mcp_atlassian/utils/logging.py
This PR addresses two critical authentication and integration issues that were blocking users from accessing the tool with Google ADK/VertexAI and Docker SSE transport.
**Fixes:** #401, #411
- **VertexAI Schema Compatibility (Issue #401)**: Fixed the `confluence_search` function's `spaces_filter` parameter schema to remove `anyOf` constructs that violated VertexAI's function calling constraints
- **Docker SSE Authentication Debugging (Issue #411)**: Added comprehensive authentication debugging logs to help users diagnose Docker SSE transport authentication failures
- **Enhanced Client Initialization**: Added masked authorization header logging and authentication validation during client initialization (debug mode only)
- **Improved Error Messages**: Enhanced authentication error messages …
> fix: resolve VertexAI schema compatibility and enhance Docker SSE authentication debugging

- tests/integration/test_transport_lifecycle.py
- tests/unit/test_main_transport_selection.py
This PR adds comprehensive test coverage for the stdio transport fix (#522) to prevent regression of issue #519. The tests verify that stdio transport correctly bypasses lifecycle monitoring while other transports use it appropriately.
Fixes: #
-
-
-
> test: add comprehensive tests for stdio transport lifecycle behavior

- src/mcp_atlassian/utils/lifecycle.py
- tests/unit/utils/test_lifecycle.py
This PR fixes the "ValueError: I/O operation on closed file" error that occurs when the MCP server shuts down, particularly on Windows or when run as a child process by Claude Desktop. The parent process can close stdio pipes before our cleanup code runs, causing the server to crash during shutdown.
Fixes: #532
- Modified `ensure_clean_exit()` in `lifecycle.py` to check if streams are closed before flushing
- Added exception handling for ValueError, OSError, and AttributeError during flush operations
- Added comprehensive test coverage for all edge cases
> fix: handle closed stdout/stderr streams gracefully during shutdown

- src/mcp_atlassian/jira/issues.py
- tests/unit/jira/test_issues.py
> fix: allow unassigning issues
