sooperset/mcp-atlassian

src/mcp_atlassian/confluence.py
src/mcp_atlassian/preprocessing.py

Fixed user mentions not being properly rendered in Confluence content by implementing proper handling of `<ac:link>` and `<ri:user>` tags. User display names are now fetched and cached from the Confluence API.
- Added user info fetching in TextPreprocessor
- Implemented caching for user display names
- Fixed HTML to Markdown conversion for user mentions

Fix user mentions rendering in Confluence content

---

src/mcp_atlassian/server.py

Fixed a TypeError that occurred when listing Confluence spaces in the resource fetcher. The error was caused by incorrectly accessing the Confluence API response structure, which nests spaces under a 'results' key.
- Added proper handling of nested 'results' structure from Confluence API
- Added type checking for API response
- Updated space access pattern to match API response format
Fixes #7

Fix Confluence spaces listing in resource fetcher

---

CHANGELOG.md
README.md
pyproject.toml
src/mcp_atlassian/__init__.py
src/mcp_atlassian/confluence.py
src/mcp_atlassian/server.py
uv.lock

This PR speed the Confluence search up by removing individual page fetching
- Remove additional API calls to fetch individual pages in search results
- Use pre-generated excerpts from Confluence search API
- Update search response format in documentation
- Update version to 0.1.7

feat: Optimize Confluence search performance

---

src/mcp_atlassian/jira.py

Fixed date parsing in the Jira fetcher to properly handle various timezone formats returned by the Jira API. The previous implementation failed to parse dates with formats like `+0000` and `+0900`.
- Enhanced `_parse_date` method to handle multiple timezone formats:
- `+0000` → `+00:00`
- `+0900` → `+09:00`
- Other similar timezone offsets (e.g., `-0500` → `-05:00`)
- Added proper error handling to return original date string if parsing fails
- Standardized date output format to `YYYY-MM-DD`
Tested with various Jira issue dates including:
- Standard UTC format (`+0000`)
- JST timezone (`+0900`)
- Other timezone offsets
#16

Fix Jira date parsing to handle various timezone formats

---

.env.example

Add guidance about avoiding double quotes in environment variable values

docs: Update .env.example with configuration note

---

src/mcp_atlassian/jira.py
src/mcp_atlassian/preprocessing.py
tests/test_jira.py
tests/test_preprocessing.py

This PR implements a complete solution for converting between Jira markup and Markdown formats in both directions.
- Added `jira_to_markdown` method to TextPreprocessor class to convert Jira markup to Markdown
- Added `markdown_to_jira` method to TextPreprocessor class to convert Markdown to Jira markup
- Updated JiraFetcher._markdown_to_jira to use the new TextPreprocessor implementation
- Enhanced clean_jira_text to use the jira_to_markdown converter
- Added comprehensive tests for both conversion directions
- Headers (h1-h6)
- Text formatting (bold, italic, strikethrough)
- Lists (ordered and unordered, with nesting)
- Code blocks (with language specification)
- Inline code
- Links and images
- Tables
- Special formatting (superscript, subscript, colored text)
- Blockquotes
- And …

feat: Implement Bidirectional Jira-Markdown Conversion

---

src/mcp_atlassian/jira.py
tests/fixtures/jira_mocks.py
tests/test_jira.py

This PR fixes failed Jira tests and replaces verbose test fixtures with simplified mock objects that are more maintainable.
- **Bug fixes**:
- Fixed `get_jira_field_ids` to properly identify "Epic Link" and "Epic Name" fields
- Enhanced `get_issue` to handle string values for `comment_limit`
- **Test improvements**:
- Replaced company-specific data with generic mocks suitable for open source
- Created simplified versions of mock responses (`MOCK_JIRA_*_SIMPLIFIED`)
- Improved test isolation to prevent tests from affecting each other
- All tests now pass reliably
- Simplified mocks improve readability and maintainability
- Tests are more resistant to API changes that don't affect core functionality
- Removed company-specific information for open source suitability
All tests pass …

Fix Jira tests and improve mock fixtures

---

.env.example
README.md
src/mcp_atlassian/config.py
src/mcp_atlassian/jira.py
tests/test_jira.py

This PR adds support for Jira Server/Data Center installations (v8.14+) while maintaining compatibility with Atlassian Cloud.
- Added Personal Access Token (PAT) authentication for Server/Data Center deployments
- Configured Bearer token authentication for on-premise installations 
- Added SSL verification control for self-signed certificates
- Enhanced JiraConfig class to support both authentication methods
- Added comprehensive documentation for Server/Data Center setup
- Added troubleshooting section for on-premise deployments
resolve #5

Add Jira Server/Data Center Support

---

README.md
src/mcp_atlassian/jira.py
src/mcp_atlassian/server.py

This PR adds support for Jira worklog functionality, allowing users to:
- Add work logs to Jira issues with time tracking
- Update remaining estimates when logging work
- Update original estimates with proper error handling
- Retrieve all worklogs for an issue
resolve #64

Add Jira worklog tools for time tracking and estimate management

---

src/mcp_atlassian/jira.py
src/mcp_atlassian/server.py

This PR adds proper support for Jira Server/Data Center deployments by changing how environment variables are checked. Previously, the code always required JIRA_USERNAME and JIRA_API_TOKEN environment variables, which are only needed for Cloud deployments.
- Update `get_available_services()` to detect instance type based on URL
- For Cloud deployments: Use JIRA_URL + JIRA_USERNAME + JIRA_API_TOKEN
- For Server/Data Center deployments: Use JIRA_URL + JIRA_PERSONAL_TOKEN
- Add logging to help diagnose authentication issues
#5

Fix Jira Server/Data Center Support

---

src/mcp_atlassian/server.py

This PR fixes issue #79 where the `confluence_get_page` tool response contained duplicate content fields when used with `include_metadata=true`.
When calling the `confluence_get_page` tool with `include_metadata=true`, the content field was duplicated in the response:
1. At the top level as `"content": page.page_content`
2. Inside the `metadata` object as part of `page.to_simplified_dict()`
- Modified the `confluence_get_page` tool implementation to only include content once:
- When `include_metadata=true`, content is only included within the metadata object
- When `include_metadata=false`, content is still returned at the top level (maintaining backward compatibility)
- Updated the code to use `page.content` instead of the deprecated `page.page_content` property
- Added a test to verify …

Fix duplicate "content" field in Confluence page metadata (#79)

---

scripts/test_with_real_data.sh
src/mcp_atlassian/server.py
tests/test_real_api_validation.py

Fixes #97
The `confluence_update_page` function was failing because it was instantiating `TextContent` without the required `type` field. This PR:
- Adds the missing `type="text"` parameter to the `TextContent` constructor in `server.py`
- Adds comprehensive test coverage for `confluence_update_page`
- Includes explicit validation for the `TextContent` class to ensure the `type` field is required
- Updates test scripts to properly handle TextContent validation
The PR includes specific tests to validate:
1. That the `TextContent` class properly requires the `type` field
2. That `confluence_update_page` works correctly with the fixed implementation
3. That we can't create a `TextContent` without the `type` field
All tests pass and the issue is resolved.

Fix confluence_update_page by adding required 'type' field to TextContent

---

README.md
pyproject.toml
src/mcp_atlassian/__init__.py
src/mcp_atlassian/server.py
uv.lock

This PR adds Server-Sent Events (SSE) transport support to mcp-atlassian, providing an alternative to the default stdio transport. This enhancement allows the MCP server to run as a standalone HTTP server that clients can connect to, making it more flexible for different integration scenarios.
- Added `--transport` CLI option to select between stdio (default) and SSE transports
- Added `--port` CLI option to configure the port for SSE transport (default: 8000)
- Implemented SSE transport using Starlette and Uvicorn
- Significantly improved documentation with:
- Clearer configuration instructions
- Setup guides for both transport types
- Visual examples for IDE integration
- Better organized installation and configuration sections
- Added new dependencies: click, uvicorn, and starlette
The …

Add SSE transport support and improve documentation

---

README.md
src/mcp_atlassian/confluence/pages.py
src/mcp_atlassian/server.py
tests/unit/confluence/test_pages.py

This PR adds a new method and tool for retrieving parent/ancestor pages in Confluence. It addresses the limitations of CQL search for parent-child relationships, which were identified in our investigation (see attached report).
- Added `get_page_ancestors` method to `PagesMixin` class
- Added `confluence_get_page_ancestors` tool to the API
- Added comprehensive unit tests for the new functionality
- Updated documentation in README.md to explain the limitations of CQL and how to use the new tool
CQL searches using `parent=` or `childId=` parameters were unreliable for finding hierarchical relationships in Confluence. This implementation uses the more reliable `/content/{id}?expand=ancestors` endpoint instead.
- Unit tests added for all edge cases (normal operation, empty ancestors, error …

Add Confluence page ancestors API and tool

---

src/mcp_atlassian/confluence/client.py
tests/unit/confluence/test_client.py

This PR implements the `get_user_details_by_accountid` method in the ConfluenceClient class, which was needed by the preprocessor to properly handle user mentions in Confluence content.
The content preprocessor requires account ID resolution to display proper user names when converting Confluence content, but the ConfluenceClient was missing this method implementation, causing fallback to generic account ID representation.
- Implemented `get_user_details_by_accountid` method in ConfluenceClient that delegates to the underlying Atlassian SDK
- Added proper type hints and documentation
- Added comprehensive unit tests for the new method
- Verified compatibility with the preprocessing protocol
- Unit tests added for the new method
- Verified all existing tests continue to pass
- Tested that …

Add user details retrieval method to ConfluenceClient

---

src/mcp_atlassian/jira/fields.py

Call [get_all_fields()](https://github.com/atlassian-api/atlassian-python-api/blob/df25ee599ed61663b667b7d3b595111a7ab01c1d/atlassian/jira.py#L688) instead of `fields()`
For example, when using the `jira_create_issue` tool with issue_type `Sub-task`, we get an error for something like this.
`ERROR:mcp-jira:Error getting Jira fields: 'Jira' object has no attribute 'fields'`

Fix call get_all_fields API in get_fields

---

scripts/test_with_real_data.sh
src/mcp_atlassian/jira/issues.py
src/mcp_atlassian/server.py
tests/test_real_api_validation.py
tests/unit/jira/test_fields.py

This PR adds support for creating subtasks in Jira, allowing users to link issues to parent tasks and properly structure their work hierarchy.
This is a follow up PR of #110.
- Add support for creating subtasks with proper parent relationship
- Update tool documentation to include subtask examples
- Add integration test for the subtask creation workflow
- Added `_prepare_parent_fields` method to handle parent-child relationships
- Updated the issue creation logic to detect subtask issue types
- Updated field processing to handle parent references
- Added detailed examples in the API description
- Fixed failing tests in the Jira fields tests (using correct method name)
- Added a new integration test `test_jira_create_subtask`
- Updated test script to run the subtask creation test
- All …

Add Jira subtask creation support

---

src/mcp_atlassian/models/jira.py
tests/unit/models/test_jira_models.py

- Add _find_custom_field_by_name method to dynamically find custom field values by name patterns, improving adaptability to different Jira configurations.
- Update epic field extraction in from_api_response to utilize the new method for better handling of varying custom field IDs.
- Enhance unit tests to cover various scenarios for custom field retrieval, including case insensitivity and pattern matching.
Contribute to the resolution of #114

Add dynamic custom field retrieval in JiraIssue

---

scripts/test_with_real_data.sh
src/mcp_atlassian/jira/issues.py
src/mcp_atlassian/server.py
tests/test_real_api_validation.py
tests/unit/jira/test_issues.py

Recent changes in Jira restricted the Parent field to only be available for Sub-tasks, breaking workflows where users needed to assign Tasks to parent issues.
- Modified the code to allow using the parent field for all issue types, not just subtasks
- Updated the `_prepare_parent_fields` method to handle non-subtask issue types without raising errors
- Modified `create_issue` to check for parent field in all issue types when explicitly provided
- Updated API documentation to clarify that parent field can be used for any issue type
- Added unit and integration tests to verify the functionality
- Added unit test: `test_create_issue_with_parent_for_task`
- Added integration test: `test_jira_create_task_with_parent`
- All tests are passing
Fixes #121

Fix to allow parent field for all issue types, not just subtasks

---

src/mcp_atlassian/confluence/config.py
src/mcp_atlassian/jira/config.py
src/mcp_atlassian/server.py
src/mcp_atlassian/utils.py
tests/integration/conftest.py
tests/integration/test_ssl_verification.py
tests/unit/confluence/test_config.py
tests/unit/jira/test_config.py
tests/unit/test_utils.py

When SSL verification was disabled (`ssl_verify=False`), connections to Atlassian Server/Data Center 
instances with self-signed certificates still failed with SSL verification errors. This was happening
because the `SSLIgnoreAdapter` wasn't properly configuring the SSL context.
The original implementation only overrode the `cert_verify` method but didn't properly configure
the SSL context. This resulted in the error: 
`Cannot set verify_mode to CERT_NONE when check_hostname is enabled`
- Properly implement the `init_poolmanager` method in `SSLIgnoreAdapter` to configure the SSL context
- Disable both hostname checking and certificate verification by setting:
- `context.check_hostname = False`
- `context.verify_mode = ssl.CERT_NONE`
- Keep the existing `cert_verify` override for backwards …

Fix: Properly implement SSL verification bypass for self-signed certificates

---

src/mcp_atlassian/server.py

I've noticed the macros (like datetime) are not visible in the markdown when using get_page_content. I added a new argument that allows to disable converting to markdown and see the page in it's raw format.

Support getting raw page format

---

.gitignore
scripts/test_with_real_data.sh
src/mcp_atlassian/jira/epics.py
src/mcp_atlassian/jira/issues.py
tests/test_real_api_validation.py
tests/unit/jira/test_epics.py
tests/unit/jira/test_issues.py

This PR addresses a regression in Epic creation functionality that occurred after implementing dynamic custom field retrieval in PR #117. While PR #117 improved the ability to read custom fields (related to issue #114), it inadvertently affected the Epic creation process.
- Implemented a two-step Epic creation approach to work around Jira API limitations:
1. Create basic Epic without custom fields
2. Update created Epic with Epic-specific fields (Epic Name, Epic Color)
- Enhanced field discovery with multiple strategies for identifying Epic-related fields
- Added comprehensive unit and integration tests
- All 372 unit tests passing
- Integration tests for Epic creation successful with custom fields
- Verified functionality across different Jira configurations
- Addresses regression …

Fix Jira Epic Creation with Two-Step Approach

---

src/mcp_atlassian/jira/search.py
src/mcp_atlassian/models/jira.py
tests/unit/jira/test_search.py

- Modified the `JiraIssue` model to store custom fields and track requested fields
- Updated the conversion pipeline to preserve field filtering throughout
- Enhanced the `to_simplified_dict` method to only return fields that were requested
- Added test to verify field filtering for both standard and custom fields
- Ensured backward compatibility with existing code
Added a unit test that verifies field filtering works correctly, including for custom fields.
Fixes #141

Fix: jira_search fields parameter to correctly filter response fields

---

.env.example
README.md

This PR updates the README documentation to:
- Focus on CLI arguments as the primary configuration method
- Reorganize IDE integration section for better clarity
- Improve configuration examples with consistent formatting
- Enhance development and debugging instructions
- Add collapsible sections for alternative configurations

Docs: Simplify README structure

---

.env.example
README.md
src/mcp_atlassian/__init__.py
src/mcp_atlassian/server.py
src/mcp_atlassian/utils.py

This PR adds a read-only mode feature to address issue #131. When enabled, this mode prevents all write operations (create, update, delete) while still allowing all read operations. This is particularly useful when working with production Atlassian instances where you want to prevent accidental modifications.
- Added `is_read_only_mode()` function to `utils.py` to check if read-only mode is enabled
- Added `--read-only` CLI flag to `__init__.py` 
- Updated server handlers in `server.py` to check for read-only mode before performing write operations
- Updated `list_tools()` to hide write operations when in read-only mode
- Updated `.env.example` file with the new environment variable
- Added documentation to README.md
Closes #131

Add read-only mode to disable write operations

---

src/mcp_atlassian/utils.py

This PR resolves an issue #148 where users encountered an SSL error `([SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1028))` when using the `--no-confluence-ssl-verify` or `--no-jira-ssl-verify` flag.
If a separate option needs to be created, or if comments or documentation updates are required, please let me know.
Fixes #148

Fix SSLError when using no SSL verify option

---

.env.example
.gitignore
README.md
src/mcp_atlassian/__init__.py
src/mcp_atlassian/confluence/config.py
src/mcp_atlassian/confluence/search.py
src/mcp_atlassian/jira/config.py
src/mcp_atlassian/jira/search.py
src/mcp_atlassian/server.py
tests/unit/confluence/test_search.py
tests/unit/jira/test_projects.py
tests/unit/jira/test_search.py

Add confluence-spaces and jira-projects filter arguments,
these filters help narrow down search results to the most relevant spaces or projects, improving response quality and performance.

Add support for jira/confluence search filter

---

.env.example
README.md
src/mcp_atlassian/__init__.py
src/mcp_atlassian/utils/logging.py
tests/unit/utils/test_logging.py

The Cline VS Code extension was unable to connect to the mcp-atlassian server, while the same configuration worked correctly with Cursor IDE and Claude Desktop. Investigation revealed that Cline interprets all STDERR output (including INFO level logs) as errors, breaking the connection.
This PR changes the default logging level from INFO to WARNING across all loggers:
- Sets default logging level to WARNING in both initialization paths
- Configures all relevant loggers (`mcp-atlassian`, `mcp.server`, `mcp.server.lowlevel.server`, `mcp-jira`) to use consistent levels
- Maintains the ability to increase verbosity with the `--verbose` flag (INFO level) or `-vv` flag (DEBUG level)
- Updates documentation to explain the logging levels and compatibility improvements
- Modified …

Fix: reduce default logging level to ensure Cline VS Code compatibility

---

src/mcp_atlassian/jira/__init__.py
src/mcp_atlassian/jira/attachments.py
src/mcp_atlassian/models/jira.py
src/mcp_atlassian/server.py
tests/unit/jira/test_attachments.py

As the title says, this adds an additional tool, which is accessible by specifying `jira_download_attachments issueId directory`.
Maybe this approach is extendible for Confluence too, as someone already requested in [https://github.com/sooperset/mcp-atlassian/issues/152](url)

Implement possibility to download attachments from JIRA

---

scripts/test_with_real_data.sh
src/mcp_atlassian/jira/epics.py
src/mcp_atlassian/jira/issues.py
src/mcp_atlassian/jira/search.py
src/mcp_atlassian/models/jira.py
src/mcp_atlassian/server.py
tests/test_real_api_validation.py
tests/unit/jira/test_epics.py
tests/unit/jira/test_issues.py
tests/unit/jira/test_search.py
tests/unit/models/test_jira_models.py

This PR adds support for retrieving custom fields and specific fields from Jira issues through the MCP Atlassian integration, addressing issue #114. 
- Added `fields`, `properties`, and `update_history` parameters to Jira get_issue methods
- Enhanced the JiraIssue model to handle custom fields properly
- Updated server.py to expose these parameters through the MCP API
- Added support for different formats of the fields parameter (string, list, tuple, set)
- Added comprehensive tests for the new functionality
- Updated existing tests to work with the new parameters
- Unit tests added for all new functionality
- Added a real API validation test `test_jira_get_issue_with_fields`
- Manually tested with various custom fields and field formats
Users can now retrieve custom fields in several …

Add support for retrieving Jira custom fields via MCP API

---

src/mcp_atlassian/models/jira.py

It seems this field could be parsed too, as it is not custom field.
@sooperset I was thinking https://github.com/sooperset/mcp-atlassian/pull/157 will resolve this problem that I had, but it seems it parses custom fields only, no? Correct me if I'm wrong.
Anyways. I've added this code to parse this missing field, but maybe it would be good if there would be some refactor so instead of fetching all the predefined fields one-by-one it could just save the whole API call and fetch it depending on which `field` under `fields` user requests? Then it'd avoid adding more fields one-by-one in the future.
LMK what you think @sooperset

Parse fixVersions field properly under "fields"

---

README.md
src/mcp_atlassian/jira/__init__.py
src/mcp_atlassian/jira/boards.py
src/mcp_atlassian/jira/search.py
src/mcp_atlassian/jira/sprints.py
src/mcp_atlassian/models/jira.py
src/mcp_atlassian/server.py
tests/unit/jira/test_boards.py
tests/unit/jira/test_search.py
tests/unit/jira/test_sprints.py

This PR add JiraSprint class and register get board , get issue from board, get sprint from board, get issue from sprint. 
Total of 4 tools.

Add `get` tool for Jira agile sprint and board

---

src/mcp_atlassian/jira/utils.py
src/mcp_atlassian/server.py

Closes #172
Fixes a JQL syntax error in `list_resources` caused by unquoted user identifiers (like emails containing '@') during startup. The `account_id` variable is now quoted in the JQL query in `src/mcp_atlassian/server.py`.

Fix #172: Quote user identifier in list_resources JQL query

---

src/mcp_atlassian/confluence/constants.py
src/mcp_atlassian/confluence/search.py
src/mcp_atlassian/confluence/utils.py
src/mcp_atlassian/server.py
tests/unit/confluence/test_search.py
tests/unit/confluence/test_utils.py

Introduces `quote_cql_identifier_if_needed` utility in
`confluence/utils.py` to correctly quote identifiers (like personal
space keys '~...', reserved words, numeric-start strings)
for safe use in CQL literal values, according to Confluence documentation.
Also handles escaping of internal quotes/backslashes.
Defines reserved CQL words in new `confluence/constants.py`.
Applies this utility in:
- `server.py` (`read_resource`) when constructing CQL queries for space URIs.
- `confluence/search.py` when processing the `spaces_filter`.
Updates tool description in `server.py` to mention quoting requirements.
Adds unit tests for the new utility and updates tests for search mixin.
Fixes #184

Fix: Add conditional quoting for CQL identifiers

---

src/mcp_atlassian/confluence/pages.py
src/mcp_atlassian/confluence/search.py
src/mcp_atlassian/exceptions.py
src/mcp_atlassian/jira/issues.py
src/mcp_atlassian/jira/search.py
src/mcp_atlassian/jira/transitions.py

This PR addresses Issue #183 by adding explicit handling for authentication errors when Atlassian API tokens expire or become invalid. Previously, when a token expired, the service would fail silently, returning empty results without indicating the authentication problem.
- Created a new `MCPAtlassianAuthenticationError` exception class
- Added specific handling for 401/403 HTTP errors in key methods:
- Jira: `search_issues`, `get_issue`, `get_available_transitions`, `transition_issue`
- Confluence: `search`, `get_page_content`, `get_page_ancestors`
- Maintained backward compatibility with existing test suite
- Updated error messages to be clear and actionable for users
Resolves #183

Fix: Add explicit authentication error reporting for expired tokens

---

src/mcp_atlassian/models/jira.py

https://github.com/sooperset/mcp-atlassian/issues/114
This PR updates the `JiraIssue` model to capture all unprocessed fields into `custom_fields`.  
- Skips known fields
- Ensures support for fields like `timetracking`, `timeestimate`, or any custom fields  
- Improves compatibility with varying Jira field configurations

Improve custom_fields handling to include all unprocessed fields

---

README.md

Fixes #174
- Updated SSE transport section to clarify that environment variables must be set on the server side
- Removed misleading `env` section from the client-side configuration example
- Added example showing how to properly configure the server with command-line arguments

Fix SSE transport documentation regarding environment variables

---

Dockerfile
README.md
smithery.yaml

**Summary:**
This PR integrates `mcp-atlassian` with [Smithery.ai](https://smithery.ai/), enabling automated deployments and easier installation for users via the Smithery CLI.
**Key Changes:**
*   **`smithery.yaml` Added:** Defines the configuration schema (URLs, credentials, filters) and the command function needed for Smithery to run the server.
*   **`README.md` Updated:** Includes a Smithery badge linking to the server page and adds a concise "Installation via Smithery" quick start section.
*   **`Dockerfile` Cleanup:** Removed the line copying `.env.example` to avoid potential conflicts with runtime environment variables injected by Smithery or Docker `--env-file`.
This allows users to leverage Smithery's hosting and installation management for this MCP server.

Feat: Configure mcp-atlassian for Smithery Deployment and Installation

---

.gitignore
README.md

This PR updates the `README.md` to use the correct `mcp-atlassian` command for running the application.
The previous instructions using `python -m mcp_atlassian` were incorrect and caused errors because the package isn't designed to be executed that way. The correct method is to use the script entry point defined in `pyproject.toml`, which is made available as the `mcp-atlassian` command after installation.
All relevant examples in the README have been updated.
Fixes #179

Fix: Correct command invocation in README (#179)

---

.github/workflows/tests.yml

Closes #87
This PR adds automated testing to our CI pipeline using `pytest`. Now, tests will run automatically on pushes and PRs to `main`, helping us catch regressions early.

CI: Add pytest workflow (#87)

---

src/mcp_atlassian/server.py

- Standardized all pagination parameters to use `startAt` in API schemas
- Converted parameters named `start` to `startAt` for consistent API experience
- Ensured all parameter descriptions use consistent wording
- Added proper type conversion for all pagination parameters
- Maintained internal function call convention using `start=start_at`
The codebase was using multiple inconsistent parameter names (`startAt`, `start_at`, and `start`) for the same pagination concept, leading to potential confusion and bugs.
This change aligns with Atlassian's API conventions (camelCase) while keeping our internal code consistent.

Unify pagination parameter names to 'startAt' across Jira tools

---

src/mcp_atlassian/jira/search.py
src/mcp_atlassian/server.py
tests/unit/jira/test_search.py

This PR addresses issue #164 by enhancing the Jira search tools to return count metadata alongside the search results.
Currently, when searching for Jira issues, the MCP tool only returns the list of issues without metadata about the total number of matching results. This prevents the AI from answering questions like "How many tickets are there in X project?" without manually counting the returned issues.
The JiraSearchResult model already captures total, start_at, and max_results from the Jira API response, but the search_issues method was only returning the issues list. This PR:
- Modifies search_issues to return the full JiraSearchResult object instead of just the issues list
- Updates all relevant MCP tools to include the metadata in their responses
- Maintains backward compatibility …

Add count metadata to Jira search results (#164)

---

src/mcp_atlassian/jira/issues.py
src/mcp_atlassian/server.py
tests/unit/jira/test_issues.py
tests/unit/test_server.py

This PR enhances the Jira component support by allowing users to specify multiple components when creating an issue. This builds on PR #207, which introduced initial support for a single component.
- Modify `IssuesMixin.create_issue()` to accept a list of components instead of a single component
- Update the `jira_create_issue` tool schema in `server.py` to use an array type for components
- Add proper filtering for invalid components (empty strings, whitespace, None values)
- Implement precedence handling when components are specified both via parameter and additional_fields
- Fix type definition for the assignee field in the schema to properly allow null values
- Add comprehensive unit tests for all new functionality
Closes #115

Enhance Jira component support to allow multiple components

---

src/mcp_atlassian/server.py
tests/unit/test_server.py

This PR addresses issue #211 where Windsurf clients are unable to parse the input schema for the `jira_create_issue` tool. The issue occurs because Windsurf has trouble parsing array-type parameters in the tool's input schema.
- Changed the `components` parameter in the `jira_create_issue` tool from an array type to a string type
- Updated the parameter description to specify it accepts a comma-separated list
- Added preprocessing logic in `server.py` to convert the comma-separated string to a list before passing to the JiraFetcher
- Updated the unit test to use the new string format while maintaining the same assertion
This approach maintains the existing behavior for all clients while making the tool compatible with Windsurf. The string-to-list conversion happens at the API boundary in …

Fix Windsurf unable to parse input schema for jira_create_issue

---

src/mcp_atlassian/jira/issues.py
src/mcp_atlassian/server.py

This PR provides a temporary workaround for issue #212 by documenting how to specify `fixVersions` when it's configured as a required field in Jira project settings.
> ⚠️ **Note**: This is a quick documentation fix only. 
- Added an example showing how to set Fix Version/s using the `additional_fields` parameter
- Example shows the correct JSON format: `{"fixVersions": [{"id": "10020"}]}`
Fix #212

Quick fix: Document fixVersions workaround for required fields

---

src/mcp_atlassian/jira/issues.py
tests/unit/jira/test_issues.py

`fixVersions` passed via `additional_fields` isn't added to the Jira API request, breaking the workaround suggested in #212. The `_add_custom_fields` method skips standard field names not found in the `field_ids` mapping.
Modified `_add_custom_fields` in `issues.py` to explicitly check for and handle `fixVersions`.
- Added specific check for `fixVersions` in `_add_custom_fields`
- Added logging for confirmation
- Added unit tests to verify the fix
Fixes #241

Fix handling of fixVersions when provided in additional_fields (#241)

---

src/mcp_atlassian/jira/users.py
tests/unit/jira/test_issues.py
tests/unit/jira/test_users.py

When creating issues in Jira Data Center/Server environments, the assignee functionality fails with the error: "Username parameter is required for user search on Jira Server". This occurs because we're using `query=username` which works for Cloud but not for Server/DC deployments.
Modified the `_lookup_user_directly` function to conditionally use:
- `query=username` for Cloud environments
- `username=username` for Server/DC environments
- Updated `_lookup_user_directly` to check `self.config.is_cloud` and use the appropriate parameter
- Added tests for both Cloud and Server/DC scenarios to ensure proper behavior
Fixes #223

Fix assignee functionality in Jira Data Center/Server during issue creation (#223)

---

src/mcp_atlassian/confluence/pages.py
src/mcp_atlassian/server.py
tests/test_real_api_validation.py
tests/unit/confluence/test_pages.py
tests/unit/test_server.py

When attaching images to Confluence pages, they were uploaded with the generic MIME type `application/octet-stream`, causing them to appear broken on the page.
- Added support for content type inference from file extensions
- Modified `confluence_attach_content` tool to accept an optional `content_type` parameter
- Added MIME type detection using Python's standard `mimetypes` library
- Implemented proper fallback to `application/octet-stream` when type cannot be inferred
- Added unit tests for content type inference from various file extensions
- Added integration test that uploads a PNG image and verifies the correct MIME type
Fixes #242

Fix: Add content type inference for Confluence image attachments (#242)

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

This PR introduces GitHub issue templates (`bug_report.yml`, `feature_request.yml`, `config.yml`) to guide users in submitting clear and informative bug reports and feature requests.
Recently, there has been an increase in issues lacking sufficient detail or relevance. These templates aim to:
- Standardize the information required for different types of issues.
- Prompt users for essential details (version, environment, steps to reproduce, use case, etc.).
- Reduce incomplete or ambiguous submissions.
- Streamline the issue triage and resolution process for maintainers.
- Added a structured YAML template for **Bug Reports** (`.github/ISSUE_TEMPLATE/bug_report.yml`).
- Added a structured YAML template for **Feature Requests** (`.github/ISSUE_TEMPLATE/feature_request.yml`).
- Added a …

Feat: Add GitHub Issue Templates

---

src/mcp_atlassian/server.py
tests/unit/test_server.py

Enhances Confluence search functionality by using `siteSearch` instead of `text` search for simple queries. This change leverages the same search mechanisms as the Confluence WebUI, providing more relevant results by default. An automatic fallback to text search ensures compatibility with older Confluence Server/Data Center versions.
Without this, simple searches on Confluence rarely return the most relevant results, making it harder for an Agent to find what's needed.
- Updated the search conversion to use `siteSearch ~ "query"` instead of `text ~ "query"` for simple terms.
- Added an automatic fallback mechanism to text search if siteSearch fails.
- Added unit tests for the updated search.
- Updated tool specs to reflect the new search behavior and fallback mechanism.
[x] Unit tests …

feat(search): use siteSearch as default with text search fallback

---

src/mcp_atlassian/server.py
tests/unit/test_server.py

This PR fixes an issue where the `jira_get_epic_issues` tool raises an `AttributeError: 'list' object has no attribute 'issues'` when processing the results returned from the Jira client's `get_epic_issues` method. The method was returning a list of JiraIssue objects, but the server code incorrectly tried to access an `.issues` attribute on this list.
Fixes: #277
- Updated `jira_get_epic_issues` handler in `server.py` to iterate directly over the list returned by `get_epic_issues` method
- Modified metadata response construction to use the list length for `total` and pass through the provided `start_at` and `limit` values
- Added a unit test to verify the fix works correctly with a list return type

Fix AttributeError in jira_get_epic_issues tool when processing list results

---

src/mcp_atlassian/models/jira/issue.py
tests/test_real_api_validation.py

This PR fixes an issue with the `jira_get_issue` tool where comments were being fetched from the Jira API but filtered out of the final response even when explicitly requested with `comment_limit > 0`. The bug was due to a field name mismatch in the serialization logic.
Fixes: #275
- Fixed `JiraIssue.to_simplified_dict()` to check for `"comment"` (singular) instead of `"comments"` (plural) to match the field name used in the `requested_fields` list
- Added integration test `test_jira_get_issue_includes_comments` to verify that comments are included when requested with `comment_limit > 0`

Fix jira_get_issue tool to include comments when requested with comment_limit

---

.dockerignore
.github/workflows/docker-publish.yml
Dockerfile
README.md

This PR adds support for publishing Docker images to GitHub Container Registry (ghcr.io) with both latest and version-specific tags. It also adds a manual trigger option for the Docker publishing workflow, providing more flexibility for CI/CD processes.
Fixes: #243
- Created `.github/workflows/docker-publish.yml` workflow file that:
- Uses GitHub Container Registry (ghcr.io) for publishing images
- Adds support for both version tags and latest tags
- Includes triggers for both tag pushes (v*.*.*) and manual workflow dispatch
- Extracts version information dynamically from Git tags or branch names
- Updated README.md with:
- Documentation for pulling versioned images from ghcr.io
- Updated Docker configuration examples for IDE integration
- Recommendations for pinning to specific version …

Add version-specific tags for container images on ghcr.io

---

.env.example
src/mcp_atlassian/__init__.py

This PR fixes an issue where the `TRANSPORT` and `PORT` environment variables were being ignored, requiring users to explicitly use command-line arguments to configure transport mode and port. The changes implement proper environment variable support with a clear precedence order and make sure PORT is only considered when relevant.
Fixes: #291
- Added logic to check for `TRANSPORT` and `PORT` environment variables after loading dotenv
- Implemented proper precedence: command-line arguments override environment variables, which override defaults
- Added conditional handling to only use `PORT` when the final transport mode is `sse`
- Updated `.env.example` file to clarify usage of these variables and their relationship

Honor TRANSPORT and PORT environment variables with proper precedence (#291)

---

src/mcp_atlassian/jira/issues.py
src/mcp_atlassian/jira/users.py
tests/unit/jira/test_users.py

This PR fixes an issue where creating Jira issues with assignees in Server/Data Center environments fails. The root cause is that `_lookup_user_directly` prioritizes returning the user's `key`, but the Jira Server/DC API expects the user's `name` when setting the assignee via `{"name": ...}` during issue creation.
Fixes: #223
- Modified `_lookup_user_directly` to prioritize returning user's `name` over `key` for Jira Server/DC environments
- Applied the same prioritization logic to `_lookup_user_by_permissions` for consistency
- Renamed variables in issue creation methods from `account_id` to `assignee_identifier` for clarity
- Added and updated unit tests to verify the correct behavior in all environments
- Added test for prioritizing name over key when both are present
- Added test for …

Fix Jira Server/DC assignee issue by prioritizing user name over key

---

src/mcp_atlassian/servers/jira.py
tests/unit/servers/test_jira_server.py

This PR fixes two issues with the Jira search tools:
1. **Parameter Mismatch**: The Jira search tools (`jira_search` and `jira_get_project_issues`) were failing with a parameter name mismatch because they passed an incorrect parameter name to the underlying methods. The tools use `start_at` as their parameter name for pagination, but the underlying methods expect `start`.
2. **Iteration Error**: When the `jira_search` tool is called, it fails with a `TypeError: 'tuple' object has no attribute 'to_simplified_dict'`. This happens because the code incorrectly iterates over the `JiraSearchResult` Pydantic model instead of its `issues` attribute, resulting in attempts to call `to_simplified_dict()` on tuple values.
Fixes: #308
- Changed `start_at=start_at` to `start=start_at` in the `search` …

Fix: Jira search pagination parameter mismatch (#308)

---

.pre-commit-config.yaml
CHANGELOG.md
README.md
pyproject.toml
src/mcp_atlassian/jira/sprints.py
src/mcp_atlassian/server.py
src/mcp_atlassian/utils/__init__.py
src/mcp_atlassian/utils/dates.py
tests/unit/jira/test_sprints.py
uv.lock

***definitely feel free to rip me up for not following standards here, python definitely isn't my usual forte***
Adding new jira_create_sprint functionality
- Added create_sprint function to sprints.py
- Added new tool jira_create_sprint
- Mapped jira_create_sprint tool call to sprints.create_sprint
I made a conscious choice to to name the date arguments (start_date, end_date), to keep them distinctly namespaced from the pagination arguments startAt/endAt. Happy to move them to camel cased if thats the preference. 
I plan to add in all the sprint updating functionality after this PR merges. I tested it out using claude3.5 and it worked great! 
One other thing that was neat, was in the Tool definition, for start/end_date, if the description has the format "(ISO 8601 format)", claude will …

fix: Added create_sprint

---

src/mcp_atlassian/server.py

This PR corrects the example JSON provided in the `jira_update_issue` tool description within `src/mcp_atlassian/server.py`. The previous example incorrectly showed the `assignee` value as a dictionary (`{"name": "..."}`). This was inconsistent with the implementation in `IssuesMixin.update_issue`, which expects a string identifier (username, email, or account ID) for the assignee.
This incorrect example caused runtime error, `AttributeError: 'dict' object has no attribute 'startswith'`, when the tool was used with the assignee provided as a dictionary. This fix resolves the inconsistency and prevents this error.
- Corrected the `assignee` example format in the `jira_update_issue` tool description (`server.py`).

Correct jira_update_issue example for assignee format

---

src/mcp_atlassian/confluence/pages.py
src/mcp_atlassian/confluence/search.py
src/mcp_atlassian/models/confluence/page.py
src/mcp_atlassian/models/confluence/search.py
tests/unit/models/test_confluence_models.py

This adds support for on-prem Confluence servers. The current code didn't work with my company's installation without these changes.
- Detects whether Confluence is cloud or server and adjusts URLs based on that.

Support on-prem servers

---

README.md
src/mcp_atlassian/confluence/__init__.py
src/mcp_atlassian/confluence/labels.py
src/mcp_atlassian/models/__init__.py
src/mcp_atlassian/models/confluence/__init__.py
src/mcp_atlassian/models/confluence/label.py
src/mcp_atlassian/server.py
tests/fixtures/confluence_mocks.py
tests/test_real_api_validation.py
tests/unit/confluence/conftest.py
tests/unit/confluence/test_labels.py
tests/unit/models/conftest.py
tests/unit/models/test_confluence_models.py

This PR adds support for labels on Confluence pages:
- get all labels on a page
- add a label to a page
Note: I am not very experienced in Python programming. Please excuse any mistakes 🙈
- Add `ConfluenceLabel` with the properties as defined in [Atlassian REST API Spec](https://developer.atlassian.com/server/confluence/rest/v900/api-group-content-labels/#api-rest-api-content-id-label-get-response):
- id (string): unique id of this label
- name (string): the actual name of the label
- prefix (string): prefix (default: global)
- label (string): I could not find a clear definition. It is mentioned in the spec. My Confluence server always returns an empty string.
- Add 2 new Tools `confluence_get_labels` and `confluence_add_label`
- Add unit and real API tests
- [✔️] Unit tests added/updated …

feat: add support for getting and adding labels for Confluence pages

---

pyproject.toml
src/mcp_atlassian/jira/search.py
tests/unit/jira/test_projects.py
tests/unit/jira/test_search.py
uv.lock

This PR fixes the TypeError: `enhanced_jql() got an unexpected keyword argument 'start'` error when using jira_search with startAt in Jira Cloud. The enhanced_jql method from atlassian-python-api doesn't support the start parameter.
Also updates atlassian-python-api dependency to version >=4.0.0.
Refs: #347
- Added conditional logic in SearchMixin.search_issues to use different methods based on environment
- Uses enhanced_jql without start parameter for Cloud environments
- Continues using jql with start parameter for Server/DC environments
- Updated parameter documentation to clarify startAt behavior in Cloud
- Updated atlassian-python-api dependency to >=4.0.0

fix(jira): Use enhanced_jql for Cloud searches and fix startAt TypeError

---

src/mcp_atlassian/jira/search.py
src/mcp_atlassian/server.py
tests/unit/jira/test_search.py

There was no way to retrieve more than 50 results from jira search. The changes added allows user to fetch more results using the `_enhanced_jql_get_list_of_tickets_` function instead of `enhanced_jql` one.
enhanced_jql uses nextPageToken to paginate the results but the token was not passed in the response.
Fixes: #
- Changed the Jira Cloud search implementation to use enhanced_jql_get_list_of_tickets instead of enhanced_jql.
- Converting the list response form the function to a structure compatible with JiraSearchResult
- Setting correct total count values based on actual results
- Preserving the requested fields in the search result model
https://github.com/user-attachments/assets/9e70c556-3b05-4be7-ba62-186f1fbe842e

Use enhanced_jql_get_list_of_tickets to allow retrieving more than 50 issues

---

README.md
src/mcp_atlassian/servers/confluence.py
src/mcp_atlassian/servers/jira.py
tests/unit/servers/test_confluence_server.py
tests/unit/servers/test_jira_server.py

This PR removes the `jira_get_epic_issues` and `confluence_get_page_ancestors` tools from the MCP server.
The `jira_get_epic_issues` tool was identified as not working reliably across different Jira instances due to variability in Epic linking fields. Both tools' functionalities can be achieved using the more general `search` tools (`jira_search` and `confluence_search`) with appropriate JQL/CQL queries. This change simplifies the available toolset for users and reduces maintenance.
Fixes: #
- Removed `get_epic_issues` tool function and registration from `src/mcp_atlassian/servers/jira.py`.
- Removed `get_page_ancestors` tool function and registration from `src/mcp_atlassian/servers/confluence.py`.
- Updated test fixtures (`test_jira_mcp`, `test_confluence_mcp`) in server unit tests to no …

Refactor: Remove jira_get_epic_issues and confluence_get_page_ancestors tools

---

src/mcp_atlassian/servers/jira.py

Closes #390
Updates the description for the `fields` parameter in the `jira_get_issue` tool to clarify that a single field name string is also a valid input. The previous description only mentioned a comma-separated list, which could cause confusion.
- Clarified the `fields` parameter description in the `jira_get_issue` tool to explicitly mention that a single field string (e.g., `"duedate"`) is a valid input, in addition to comma-separated lists or `*all`.
- Updated the Args section in the docstring for the `fields` parameter to maintain consistency.
- Tested locally using MCP Inspector to call the `jira_get_issue` tool with:
- `fields="duedate"`: Verified correct behavior.
- `fields="summary,status"`: Verified correct behavior.
- `fields="*all"`: Verified correct behavior.
- …

docs(jira): Improve field description in get_issue function

---

src/mcp_atlassian/servers/jira.py

Clarifies expected format for `assignee` field in Jira tools to resolve user confusion.
Fixes: #391
- Updated `assignee` parameter description in `jira_create_issue` schema
- Updated `fields` parameter description in `jira_update_issue` schema to explain `assignee` format
- Made explicit that string identifiers (email, name, or accountId) are expected

docs(jira): Clarify assignee field description in tool schemas (#391)

---

README.md

This PR temporarily removes OAuth 2.0 authentication documentation from the README.
Recent testing revealed some issues with the OAuth flow in Docker environments. To prevent user frustration with an unverified setup process, we're hiding these sections until we can fully validate the implementation.
Once testing is complete and any issues are resolved, we'll restore the documentation with any necessary updates.

docs: Temporarily hide OAuth documentation until fully verified

---

src/mcp_atlassian/servers/confluence.py
src/mcp_atlassian/servers/jira.py
src/mcp_atlassian/utils/__init__.py
src/mcp_atlassian/utils/decorators.py
tests/unit/servers/test_confluence_server.py
tests/unit/servers/test_jira_server.py

Fix compatibility issues with MCP clients (like Cursor IDE) that can't properly handle optional parameters with Union types and None defaults. Introduces a decorator that converts empty values to None.
Fixes: #389
- Added `convert_empty_defaults_to_none` decorator in utils
- Updated optional parameters in tools to use empty defaults instead of None
- Applied decorator to affected Confluence and Jira tool functions

fix: Adapt optional tool parameters for wider MCP client compatibility

---

.env.example
README.md

Revert OAuth 2.0 authentication documentation with clearer instructions in `.env.example` and `README.md` to streamline the user setup experience.
Refs #404 
- Restructured `.env.example` with comprehensive OAuth 2.0 setup guidance
- Revert "OAuth 2.0 Authentication" section to README's Quick Start Guide

docs: revert OAuth 2.0 documentation

---

.github/workflows/stale.yml

This PR adds a GitHub Actions workflow (`stale.yml`) to automatically mark inactive issues and pull requests as stale after 14 days of inactivity. The workflow helps keep the repository clean by highlighting items that may no longer be relevant.
Refs #330 
- Adds `.github/workflows/stale.yml` to configure the stale bot.
- Sets issues and PRs to be marked as stale after 14 days of inactivity.
- Disables automatic closing of stale items for now.
- Configures exemption labels and custom stale messages.

Add GitHub Actions workflow to manage stale issues and PRs

---

src/mcp_atlassian/servers/confluence.py
tests/unit/servers/test_confluence_server.py

Enhances the `confluence_get_page` tool to allow retrieving a Confluence page by either its numeric `page_id` or by specifying both `title` and `space_key`. This improves usability for users and LLMs who may not know the page ID.
Fixes: #335
- Made `page_id` optional; added `title` and `space_key` as alternative parameters.
- Added validation to ensure correct parameter combinations.
- Updated parameter descriptions for clarity.
- Applied `@convert_empty_defaults_to_none` for robust input handling.
- Consistent JSON response for both lookup methods.
- Expanded and updated unit tests for all new behaviors and error cases.

feat: Enhance confluence_get_page tool to support lookup by page title and space key

---

src/mcp_atlassian/servers/confluence.py
src/mcp_atlassian/servers/jira.py
src/mcp_atlassian/utils/decorators.py
tests/unit/utils/test_decorators.py

This PR addresses an `AttributeError: 'JiraConfig' object has no attribute 'read_only'` that occurred in Jira write tools and standardizes read-only mode checks across all Jira and Confluence write-enabled tools.
The `read_only` flag was previously moved to `MainAppContext`, but Jira tools were still attempting to access it via `jira.config.read_only`. This PR introduces a `@check_write_access` decorator that correctly uses the application context for these checks. This decorator has now been applied to all write tools in both `src/mcp_atlassian/servers/jira.py` and `src/mcp_atlassian/servers/confluence.py`, ensuring consistent behavior and cleaner code.
Fixes: #434
-   **New Decorator:**
-   Created `@check_write_access` in `src/mcp_atlassian/utils/decorators.py` to handle read-only mode …

fix: Resolve AttributeError by using context for read-only check in Confluence and Jira tools

---

src/mcp_atlassian/confluence/config.py
src/mcp_atlassian/jira/config.py
src/mcp_atlassian/servers/main.py

This PR addresses an issue where tools for Jira or Confluence services were listed (`tools/list`) even if the respective service was not fully or correctly authenticated. For example, if only `JIRA_URL` was provided without any authentication tokens, Jira tools would still appear as available. This could lead to user confusion, especially in single-service setups or when a configuration is incomplete.
This change ensures that only tools for fully authenticated services are listed.
Fixes:
- **Added `is_auth_configured()` method to `JiraConfig` and `ConfluenceConfig`:**
- This new method checks if all required authentication details (e.g., tokens, OAuth client credentials, cloud_id) are present and valid for the chosen `auth_type`.
- **Updated Server Lifespan (`main_lifespan`):**
- The …

Refactor: Improve Tool Listing by Validating Service Authentication

---

src/mcp_atlassian/models/jira/issue.py
tests/fixtures/jira_mocks.py
tests/unit/jira/test_issues.py
tests/unit/jira/test_search.py
tests/unit/models/test_jira_models.py

This PR enhances the `JiraIssue` model to consistently include human-readable names for custom fields, alongside their values, by utilizing the `names` map from the Jira API response. Custom fields are now always keyed by their `customfield_XXXXX` ID, with values stored as `{'value': <api_value>, 'name': <readable_name>}`.
This change improves data richness and resolves inconsistencies related to custom field representation (#440).
Fixes: #440
- `JiraIssue.from_api_response`: Now uses the API's `names` map to store custom field display names along with their values.
- `JiraIssue.to_simplified_dict`: Outputs custom fields with their `customfield_XXXXX` ID as the key and a structured value `{"value": ..., "name": ...}`. Logic for `requested_fields` updated accordingly.
- …

feat(jira): include human-readable names for Jira custom fields

---

src/mcp_atlassian/__init__.py

This pull request introduces a `--version` command-line option to the `mcp-atlassian` CLI. This allows users to easily check the installed version of the server, which is helpful for updates and diagnostics, similar to the functionality present in other MCP servers like `github-mcp-server`.
Fixes: #448
- Added `@click.version_option` to the `main` CLI command in `src/mcp_atlassian/__init__.py`.
- Configured the `prog_name` to "mcp-atlassian" for consistent version output.
- The `__version__` string already defined in the module is used to provide the version information.
- Built the package locally and ran `uv run mcp-atlassian -- --version`. Verified correct version output.
- Ran `uv run mcp-atlassian -- --help`. Verified `--version` option is listed.
- Built a Docker image with the …

feat: Add --version flag to display CLI version (#448)

---

README.md
src/mcp_atlassian/jira/projects.py
src/mcp_atlassian/models/jira/version.py
src/mcp_atlassian/servers/jira.py
tests/unit/jira/test_projects.py
tests/unit/servers/test_jira_server.py

Hi @sooperset - I have some wishlist items for this repo I want to help out with surrounding release versions. There is some really good automation opportunities here for larger Jira workflows with regulated releases like mine. MCP support for project versions (a.k.a. Releases or Fix Versions in JIRA) is a good starting point. Looking to have a few more PRs to extend this functionality further.
- Added **get_project_versions** in  to retrieve and simplify project version data
- Introduced **JiraVersion** model for parsing API responses and producing simplified output
- Exposed new **jira_get_project_versions** FastMCP tool endpoint in 
- Added unit tests covering success, empty results, and error scenarios for version listing
Let me know if there are any issues.

feat: list Jira project versions (Milestone 1)

---

.env.example
README.md

Improves user experience by reordering authentication methods in documentation to prioritize the simplest and most reliable option for new users. API Token authentication is now positioned as the recommended default method for Atlassian Cloud, while OAuth 2.0 is repositioned as an advanced option.
- Reordered authentication methods in README.md and .env.example with API Token as Method 1 (Recommended)
- Moved OAuth 2.0 from Method 1 to Method 4 (Advanced) with explanatory notes
- Added guidance notes explaining OAuth complexity vs API Token simplicity
- Updated authentication precedence order in .env.example comments
- Minor reorganization of tools table for better logical grouping

docs: Reorganize authentication methods with API Token as recommended default

---

src/mcp_atlassian/confluence/pages.py
src/mcp_atlassian/preprocessing/confluence.py
tests/test_preprocessing.py
tests/unit/confluence/test_pages.py

This PR fixes a critical issue where Confluence page updates were breaking content styling due to automatic anchor generation during markdown-to-storage format conversion. The problem occurred when `heading_anchors=True` was set in the ConfluenceConverterOptions, causing unexpected content modifications that affected colored highlights, code blocks, and other styled elements.
The fix disables automatic anchor generation by default while providing an optional parameter for users who need this functionality.
**Fixes:** #488
- Set `heading_anchors=False` by default in `ConfluencePreprocessor.markdown_to_confluence_storage()`
- Add optional `enable_heading_anchors` parameter to control anchor generation behavior
- Update `create_page()` and `update_page()` methods to support the new anchor …

fix(confluence): disable automatic heading anchors to preserve page styling

---

README.md
src/mcp_atlassian/confluence/search.py
src/mcp_atlassian/models/confluence/__init__.py
src/mcp_atlassian/models/confluence/user_search.py
src/mcp_atlassian/servers/confluence.py
src/mcp_atlassian/utils/decorators.py
tests/unit/confluence/test_search.py
tests/unit/servers/test_confluence_server.py

Adds a new `confluence_search_user` tool to search Confluence users via CQL queries, with architectural improvements to error handling across the codebase. Core functionality originally implemented by @lucinvitae in #479.
- Added new `confluence_search_user` tool for searching Confluence users using CQL
- Implemented auto-conversion of simple search terms to CQL format
- Added comprehensive user data return (account ID, display name, email, profile picture)
- Created reusable `handle_atlassian_api_errors` decorator in `utils/decorators.py`
- Centralized common error patterns across Confluence and Jira modules
- Enhanced authentication error messages with specific `MCPAtlassianAuthenticationError` handling
- Established single source of truth for Atlassian API error handling
Core …

feat: add search_user tool with improved error handling architecture

---

CONTRIBUTING.md
src/mcp_atlassian/jira/issues.py
tests/unit/jira/test_issues.py

This PR adds logic to the `jira_get_issue` to have it honor the project filter configuration such that when a request for a Jira Issue is rejected if it's prefix does NOT match any project filters (if defined). 
The user's request should NOT be able to override this.
Fixes: #478 
- Modified the CONTRIBUTING.md to align use standard markdown numbers and key steps I needed to get it the env operational
- Modify jira/get_issue logic to honor the project filter config
- Added a unit test

Feature: update jira_get_issue to honor the project filter

---

src/mcp_atlassian/confluence/pages.py
src/mcp_atlassian/confluence/v2_adapter.py
tests/unit/confluence/conftest.py
tests/unit/confluence/test_pages.py

This PR fixes critical OAuth authentication failures when creating, updating, or deleting Confluence pages. The issue was caused by Atlassian removing deprecated v1 API endpoints (`/rest/api/content`) for OAuth authentication paths, while maintaining them for API token authentication.
OAuth users were encountering "This deprecated endpoint has been removed" errors, making page operations impossible. This fix implements dual-path authentication routing to use v2 API endpoints for OAuth and maintain v1 endpoints for token/basic authentication.
**Fixes:** #429, #474
- Added `ConfluenceV2Adapter` class to handle v2 API calls for OAuth authentication
- Implemented authentication-aware routing in `PagesMixin` (OAuth → v2 API, token/basic → v1 API)
- Added v2 API support for `create_page`, …

fix(confluence): resolve deprecated API endpoints for OAuth authentication

---

README.md
src/mcp_atlassian/servers/jira.py
tests/unit/servers/test_jira_server.py

Adds get_all_projects MCP tool to retrieve all Jira projects accessible to the current user.
Many existing MCP tools require project keys as input (e.g., create_issue, get_project_issues), but there was no way for users to discover what projects they have access to. This tool fills that gap by enabling project discovery before using project-specific tools.
- Uses existing ProjectsMixin.get_all_projects() method
- Includes optional include_archived parameter (defaults to false)
- Returns JSON array of project objects with keys, names, descriptions, etc.
- Follows existing codebase patterns and conventions
The tool correctly lists projects in my Jira account

feature: Tool to list available jira projects

---

src/mcp_atlassian/__init__.py

This PR fixes a critical issue where the MCP Atlassian server fails immediately when running in Docker containers with stdio transport. The lifecycle monitoring introduced in PR #514 conflicts with the MCP server's internal stdio handling, causing a race condition that results in "I/O operation on closed file" errors.
Fixes: #519
-
-
-

fix: resolve stdio transport conflict with lifecycle monitoring

---

tests/integration/test_transport_lifecycle.py
tests/unit/test_main_transport_selection.py

This PR refactors the transport lifecycle tests from #523 to align with the simplified architecture introduced in #528. After stdin monitoring was completely removed, the original tests were over-engineered and contained redundant checks for behavior that no longer exists.
The refactoring maintains the same level of protection against regression of issues #519 (stdio transport conflicts) and #524 (HTTP session termination) while significantly reducing complexity and improving maintainability.
Related to: #523, #528, #519, #524
- **Consolidated redundant tests**: Merged 5 separate transport tests into a single parameterized test since all transports now behave identically
- **Removed obsolete tests**: Eliminated tests for stdin monitoring functionality that no longer exists
- **Added …

refactor: simplify transport lifecycle tests after stdin monitoring removal

---

src/mcp_atlassian/servers/confluence.py
tests/unit/servers/test_confluence_server.py

This PR fixes an issue where LLM clients (like Gemini) send numeric parent IDs as integers when creating or updating Confluence pages, causing Pydantic validation failures. The fix adds a `BeforeValidator` to automatically convert numeric inputs to strings, making the API more robust and LLM-friendly.
The issue occurred because:
1. LLMs naturally parse purely numeric values (like "123456789") as integers in JSON
2. Pydantic v2's strict type checking rejects integers for string fields
3. User workarounds (telling LLM to "quote it") resulted in malformed IDs like "'123456789'"
Fixes: #452
- Added `BeforeValidator` import from pydantic to `confluence.py`
- Added validator to `parent_id` field in `create_page` function to convert numeric values to strings
- Added validator to `parent_id` …

fix: handle numeric parent_id values in Confluence page operations

---

src/mcp_atlassian/jira/epics.py
src/mcp_atlassian/jira/issues.py
src/mcp_atlassian/jira/protocols.py
tests/unit/jira/test_client_oauth.py

This PR fixes test failures that occur when running against Jira instances configured in non-English languages. The issue was that the code was doing exact string matching for issue types like "Epic" and "Subtask", but these are localized in non-English Jira instances (e.g., "에픽" and "하위 작업" in Korean).
Related to: #537, #536
- Add dynamic issue type resolution in `create_issue()` that queries the API to find localized names
- Update Epic validation logic to handle multiple language variants
- Add `ProjectsOperationsProto` protocol for proper type checking
- Fix OAuth configuration test to properly isolate environment variables

fix: handle localized issue type names for Epic and Subtask

---

src/mcp_atlassian/servers/jira.py

This PR completes the removal of the `convert_empty_defaults_to_none` decorator that was started in #515 . One function (`create_remote_issue_link`) was missed in the original refactoring, causing test failures in CI/CD due to missing import errors.
Fixes: #542
- Removed `@convert_empty_defaults_to_none` decorator from `create_remote_issue_link` function
- Updated optional parameters to use `str | None` type with `None` defaults instead of empty strings
- Ensures consistency with the refactoring pattern established in #515

fix: complete removal of convert_empty_defaults_to_none decorator

---

src/mcp_atlassian/jira/projects.py
src/mcp_atlassian/jira/search.py
tests/unit/jira/test_projects.py
tests/unit/jira/test_search.py

Quote project name when accessing JIRA. This solves a bug where you can't request stuff from a project whose name is also a reserved keyword in JQL.
Quote project name in 2 JQLs.

in JQL, need to quote project name (usually forgiven but not always)

---

.env.example
README.md
src/mcp_atlassian/confluence/client.py
src/mcp_atlassian/confluence/config.py
src/mcp_atlassian/jira/client.py
src/mcp_atlassian/jira/config.py
src/mcp_atlassian/utils/env.py
tests/unit/confluence/test_custom_headers.py
tests/unit/jira/test_custom_headers.py
tests/unit/utils/test_custom_headers.py

Fixes #436
Added support for configuring custom HTTP headers for both Jira and Confluence API requests. This feature enables users, especially in corporate environments, to add required authentication, routing, or security headers.
---
:hammer_and_pick: with :heart: by [Siemens](https://opensource.siemens.com/)

feat: add support for configuring custom HTTP headers

---

src/mcp_atlassian/jira/epics.py
src/mcp_atlassian/jira/fields.py
src/mcp_atlassian/jira/issues.py
src/mcp_atlassian/jira/protocols.py
tests/unit/jira/test_epics.py
tests/unit/jira/test_issues.py
tests/unit/jira/test_protocols.py
uv.lock

This PR fixes Epic creation failures when the Epic Name field is customized and marked as required in Jira. The current implementation uses a two-step approach where Epic-specific fields are added after initial creation, but this fails when Epic Name is a required field because Jira rejects the creation request with missing required fields.
Fixes: #457
- Modified `prepare_epic_fields` method to check field requirements using existing `get_required_fields` method
- Added `project_key` parameter to `prepare_epic_fields` to enable field requirement lookup
- Updated `_prepare_epic_fields` in `IssuesMixin` to extract and pass project_key
- Added logic to include required Epic fields during initial creation while keeping optional fields for post-creation update
- Updated `EpicOperationsProto` …

fix: handle required Epic Name fields during creation

---

src/mcp_atlassian/confluence/client.py
src/mcp_atlassian/confluence/comments.py
src/mcp_atlassian/confluence/pages.py
src/mcp_atlassian/confluence/search.py
src/mcp_atlassian/preprocessing/base.py
src/mcp_atlassian/preprocessing/confluence.py
tests/test_preprocessing.py
tests/unit/confluence/test_client.py
tests/unit/confluence/test_pages.py

This PR fixes a circular reference between `ConfluenceClient` and `ConfluencePreprocessor` that was preventing proper garbage collection and causing memory leaks in long-running processes.
The preprocessor was storing a reference to the client, which in turn held a reference to the preprocessor, creating a circular dependency that Python's garbage collector couldn't break.
Relevant issue: #532
- Removed `confluence_client` parameter from `BasePreprocessor.__init__`
- Updated `process_html_content` and related methods to accept client as parameter
- Modified all calling code in mixins to pass client when needed
- Aligned implementation with `JiraPreprocessor` pattern

fix: eliminate circular reference in Confluence preprocessor

---

src/mcp_atlassian/jira/search.py
tests/unit/jira/test_search.py

This PR fixes an issue where the Jira search tool would generate invalid JQL syntax when using the `JIRA_PROJECTS_FILTER` environment variable or `projects_filter` parameter with empty queries or queries starting with `ORDER BY`.
Fixes: #573
- Modified JQL construction logic in `search_issues()` to detect and handle empty/None JQL queries
- Added special handling for JQL queries that start with `ORDER BY` clause
- Added comprehensive test coverage for both scenarios with single and multiple projects

fix: handle empty JQL and ORDER BY clauses with project filters

---

src/mcp_atlassian/jira/config.py
tests/unit/jira/test_config.py

This PR fixes an issue where `jira_get_user_profile` fails in Multi-Cloud OAuth mode when called with an email address. The API was incorrectly using the `username` parameter instead of `accountId` for Jira Cloud instances.
Fixes: #560, #580
- Updated `JiraConfig.is_cloud` property to correctly identify Multi-Cloud OAuth as a Cloud instance
- OAuth configurations with `cloud_id` now always return `True` for `is_cloud` check
- Added unit test to verify OAuth cloud detection behavior
In Multi-Cloud OAuth mode, the `JIRA_URL` environment variable may be None or empty, but the actual API URL used is `https://api.atlassian.com/ex/jira/{cloud_id}` which is definitely a Cloud URL. The fix ensures that when OAuth is configured with a cloud_id, it's always treated as a Cloud instance, regardless …

fix: use accountId parameter for user lookups in Jira Cloud OAuth mode
